
export const VIDEO_STYLES = [
  "Performance",
  "Narrative",
  "Concept",
  "Lyric Video",
  "Live Performance",
  "Animated",
  "One-Take / Long Shot",
  "Found Footage / Documentary",
  "Psychedelic / Abstract",
  "Minimalist",
  "High Fashion / Vogue",
  "Cinematic",
  "Dance-centric",
  "Surrealist",
  "Retro / Vintage",
  "Futuristic / Sci-Fi",
  "Gothic / Dark",
  "Behind-the-Scenes",
  "Split Screen",
  "Interactive / VR"
];

export const ART_STYLES = [
  "Abstract",
  "Anime",
  "Animated (2D)",
  "Animated (3D)",
  "Art Deco",
  "Art Nouveau",
  "Baroque",
  "Brutalism",
  "Charcoal Sketch",
  "Claymation",
  "Collage",
  "Comic Book",
  "Crochet",
  "Cubism",
  "Cyberpunk",
  "Dieselpunk",
  "Double Exposure",
  "Drone Videography",
  "Expressionism",
  "Fantasy",
  "Felt",
  "Film Noir",
  "Glitch Art",
  "Gothic",
  "Graphic Novel",
  "Hand-drawn animation",
  "Hyperrealism",
  "Impressionism",
  "Infrared Photography",
  "Ink Wash",
  "Light Painting",
  "Long Exposure Photography",
  "Macro Photography",
  "Minimalism",
  "Montage",
  "Oil Painting",
  "Papercraft",
  "Pencil Drawing",
  "Photography",
  "Photorealism",
  "Pixel Art",
  "Pop Art",
  "Puppetry",
  "Realism",
  "Renaissance",
  "Rococo",
  "Romanticism",
  "Rotoscoping",
  "Sand animation",
  "Sci-Fi",
  "Steampunk",
  "Stop Motion",
  "Surrealism",
  "Synthwave",
  "Thermal Imaging",
  "Vaporwave",
  "Vector Art",
  "Vintage (1920s-1980s)",
  "Watercolor",
];